spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/sweat"
    username: sweatadmin
    password: password

logging:
  level:
    org.zalando.logbook: TRACE