spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/sweat"
    username: sweatadmin
    password: password

logbook:
  format.style: json

logging:
  level:
    org:
      springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
      zalando.logbook: TRACE
      hibernate.SQL: DEBUG